spring.application.name=apoiodigital

spring.ai.google.genai.api-key=${APIKEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite
spring.ai.google.genai.chat.options.response-mime-type=application/json

# mysql
spring.datasource.url=jdbc:mysql://localhost:3306/ApoioDigitalDB
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# SQL SERVER
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ApoioDigitalDB;encrypt=false;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=*123456HAS*
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB

jwt.secret=A{,>TPPBZ[)c>^b@Y{Q>MeqNtVm6@_Y?!#@pR^+/xA>
ia-base-url=http://localhost:5000/api/assist
jwt.expiration-ms=900000

#server.address=0.0.0.0
server.port=8080

